name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  pr_presubmit:
    runs-on: ubuntu-18.04
    container:
      image: "python:3.5-buster"

    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: ./kokoro/rodete/fetch_dependencies.sh
    - name: setup build directory
      run: meson build
    - name: build
      run: ninja -C build
    - name: test
      run: meson test -C build
